import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { MdAutoAwesome, MdClose, MdSend } from "react-icons/md";
import { answerFromCV } from "../data/cvAnswers";
import { profile } from "../data/profile";
import "./styles/AskAI.css";

type Message = { role: "visitor" | "assistant"; text: string; source?: string };
const suggestions = ["What is Pankaj’s AI experience?", "Which cloud platforms does he use?", "What certifications does he have?", "How can I contact Pankaj?"];
export default function AskAI() {
  const dialog = useRef<HTMLDialogElement>(null);
  const input = useRef<HTMLInputElement>(null);
  const launcher = useRef<HTMLButtonElement>(null);
  const log = useRef<HTMLDivElement>(null);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [open, setOpen] = useState(false);
  useEffect(() => {
    if (open) { dialog.current?.showModal(); input.current?.focus(); }
    else if (dialog.current?.open) { dialog.current.close(); launcher.current?.focus(); }
  }, [open]);
  useEffect(() => { if (log.current) log.current.scrollTop = log.current.scrollHeight; }, [messages]);
  const ask = (text: string) => {
    const trimmed = text.trim().slice(0, 500);
    if (!trimmed) return;
    const result = answerFromCV(trimmed);
    setMessages((previous) => [...previous.slice(-18), { role: "visitor", text: trimmed }, { role: "assistant", text: result.answer, source: result.source }]);
    setQuestion(""); input.current?.focus();
  };
  return createPortal(<>
    <button ref={launcher} className="ask-ai-launcher" data-cursor="disable" onClick={() => setOpen(true)} aria-haspopup="dialog" aria-expanded={open}><MdAutoAwesome /> Ask AI</button>
    <dialog ref={dialog} className="ask-ai-dialog" aria-labelledby="ask-ai-title" onCancel={() => setOpen(false)} onClose={() => setOpen(false)}>
      <header><div><span className="ask-ai-eyebrow">PANKAJ’S PORTFOLIO</span><h2 id="ask-ai-title">Ask about my experience</h2></div><button type="button" className="ask-ai-close" aria-label="Close assistant" onClick={() => setOpen(false)}><MdClose /></button></header>
      <p className="ask-ai-disclosure">CV assistant · Answers are matched locally from the supplied CV, not generated by a live AI model. Your questions stay in this browser session.</p>
      <div ref={log} className="ask-ai-messages" role="log" aria-label="Conversation" aria-live="polite">
        {messages.length === 0 && <div className="ask-ai-welcome"><MdAutoAwesome /><h3>Explore the experience behind the work.</h3><p>Ask about cloud architecture, AI, projects or qualifications.</p></div>}
        {messages.map((message, index) => <div key={index} className={`ask-ai-message ${message.role}`}><span>{message.role === "visitor" ? "You" : "CV assistant"}</span><p>{message.text}</p>{message.source && <small>Source: {message.source}</small>}</div>)}
      </div>
      <div className="ask-ai-suggestions">{suggestions.map((item) => <button key={item} onClick={() => ask(item)}>{item}</button>)}</div>
      <form onSubmit={(event) => { event.preventDefault(); ask(question); }}><label className="ask-ai-input-label" htmlFor="cv-question">Your question</label><div className="ask-ai-input-row"><input ref={input} id="cv-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about skills, projects or experience…" maxLength={500} autoComplete="off" /><button type="submit" aria-label="Send question" disabled={!question.trim()}><MdSend /></button></div></form>
      <footer><a href={profile.resume} target="_blank" rel="noreferrer">Read CV</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><button onClick={() => { setMessages([]); setQuestion(""); input.current?.focus(); }}>Clear chat</button></footer>
    </dialog>
  </>, document.body);
}
