import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from '/Users/preeti/.codex/plugins/cache/openai-primary-runtime/presentations/26.923.10815/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/preeti/ai/3d-portfolio-main', build=root+'/.kong-build', skill='/Users/preeti/.codex/plugins/cache/openai-primary-runtime/presentations/26.923.10815/skills/presentations';
const font=resolvePresentationFont();
const p=Presentation.create({slideSize:{width:1280,height:720}});
const navy='#102D35', teal='#007E76', muted='#52676C';
function tx(s,text,x,y,w,h,size=26,color=navy,bold=false){const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=text;t.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return t;}
function base(title,n){const s=p.slides.add();s.background.fill='#F7F9F8';tx(s,'KONG API + AI GATEWAY',60,28,1000,28,16,teal,true);tx(s,title,60,77,1160,104,42,navy,true);tx(s,String(n).padStart(2,'0'),1170,670,50,25,16,muted);return s;}
let s=base('Three-year investment: $800k for managed Kong',1);
const vals=[['Cost comparison','Three years'],['Existing gateway infrastructure + operations','< $300k'],['Existing documentation solution','$105k'],['Combined current baseline','< $405k'],['Managed Kong API + AI platform','$800k'],['Additional investment','> $395k']];
const t=s.tables.add({rows:6,columns:2,left:60,top:200,width:770,height:342,columnWidths:[580,190],values:vals});
for(let r=0;r<6;r++){t.rows[r].height=57;for(let c=0;c<2;c++){let cell=t.getCell(r,c);cell.fill=r===0?navy:r===5?'#DDEEE9':'#FFFFFF';cell.text.style={typeface:font,fontSize:23,color:r===0?'#FFFFFF':navy,bold:r===0||r===5};}}
t.borders.assign({fill:'#DCE4E2',width:1});
tx(s,'$105k',890,213,330,76,62,teal,true);tx(s,'Potential documentation\ncost retirement over 3 years',890,299,320,90,26,navy,true);tx(s,'The remaining premium funds managed operations and additional API + AI capabilities.',890,420,320,140,25,muted);
tx(s,'Assumptions: $35k documentation cost is annual and separate from the < $100k gateway baseline. Flat run rate. Full retirement starts in Year 1. Confirm $800k includes transition and retained internal costs.',60,591,1140,66,18,muted);
s.speakerNotes.textFrame.setText('Source: user-provided planning figures. Annual gateway infrastructure and operations cost is below $100,000. Documentation cost is $35,000, assumed annual and additional to gateway costs. Kong three-year managed TCO is $800,000. 35,000 × 3 = 105,000. Current combined baseline is below 405,000, so incremental cost exceeds 395,000. The $105,000 is already reflected in this comparison and must not be deducted again. Current baseline excludes future AI additions. Catalogue replacement is conditional on scope, migration and actual cost retirement. Confirm full TCO inclusion of migration, integration, transition overlap and retained staff effort.');
s=base('Managed operations and additional platform capabilities',2);
const rows=[['Managed infrastructure','Kong handles infrastructure operations and patching within the contracted scope. Internal teams retain application integration and policy ownership.'],['Less custom platform work','Reduce future maintenance and development where Kong replaces capabilities built around Spring Cloud Gateway.'],['Additional AI gateway','Provide shared AI access and consumption controls, with usage visibility for planned AI applications. Confirm feature entitlement.'],['API catalogue','Replace the documentation solution and improve API discovery, ownership visibility and reuse.']];
rows.forEach((r,i)=>{let y=207+i*101;tx(s,r[0],60,y,330,64,27,teal,true);tx(s,r[1],425,y,780,86,26,navy);});
tx(s,'Expected qualitative value: more engineering capacity for business applications and less dependence on specialist gateway knowledge.',60,630,1110,54,21,muted);
s.speakerNotes.textFrame.setText('Managed infrastructure, infrastructure operations and patching scope is supplied by the user and remains subject to the contract. Benefits are qualitative expectations, not measured savings. Spring Cloud Gateway is a gateway framework: the comparison includes the custom engineering and operations around the current implementation. Do not claim that Spring cannot proxy AI traffic. The current implementation lacks the additional AI management capabilities described in the conversation. Kong capability reference: https://developer.konghq.com/ai-gateway/ . Spring reference: https://docs.spring.io/spring-cloud-gateway/reference/index.html . Catalogue entitlement and replacement coverage require confirmation.');
s=base('Investment case and decision criteria',3);
tx(s,'The case for the premium',60,211,530,42,30,teal,true);
tx(s,'Managed service ownership reduces internal platform responsibilities. The API catalogue replaces an existing cost, while AI gateway capabilities support the planned AI roadmap.',60,271,515,168,28);
tx(s,'Historical development explains the current platform’s investment. It is a sunk cost. Future work avoided is the relevant benefit.',60,485,515,115,25,muted);
tx(s,'Evidence required for approval',670,211,545,42,30,teal,true);
const evidence=['Confirm managed scope, support commitments and complete three-year TCO.','Validate catalogue replacement and retire the $35k annual cost.','Demonstrate required API and AI use cases in a focused pilot.','Compare Kong with retaining Spring and adding an AI gateway.'];
evidence.forEach((e,i)=>{tx(s,String(i+1),670,272+i*83,36,39,25,teal,true);tx(s,e,719,272+i*83,486,72,25);});
tx(s,'Recommendation: base approval on capability fit and service accountability. Measure operational effort and onboarding time during the pilot.',60,628,1110,58,22,navy,true);
s.speakerNotes.textFrame.setText('Qualitative business case rather than a quantified ROI claim. User states monetary benefits cannot be reliably quantified. Historical development costs are sunk and cannot be counted as future savings. Existing operations effort already included in the annual baseline must not be counted twice. AI provider consumption costs should use consistent demand assumptions across alternatives. Suggested pilot measurements: application onboarding time, internal operating hours, documentation adoption and coverage of required policies. No measured improvement or payback period is asserted.');
const candidate=build+'/candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:root+'/output/Kong_Managed_API_AI_Business_Case.pptx',pythonExecutable:'/Users/preeti/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit','--require-native-table-slide','1'],explicitTotalSlideCount:3,requiredNativeTableOwnerSlides:[1],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/validation.json'});
for(let i=0;i<3;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(build+`/slide-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
console.log('Created deck');
