import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from '/Users/preeti/.codex/plugins/cache/openai-primary-runtime/presentations/26.923.10815/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/preeti/ai/3d-portfolio-main', build=root+'/.kong-build', skill='/Users/preeti/.codex/plugins/cache/openai-primary-runtime/presentations/26.923.10815/skills/presentations';
const font=resolvePresentationFont(); const p=Presentation.create({slideSize:{width:1280,height:720}});const navy='#102D35',teal='#007E76',muted='#52676C';
function tx(s,text,x,y,w,h,size=26,color=navy,bold=false){const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=text;t.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return t;}
function base(title,n){const s=p.slides.add();s.background.fill='#F7F9F8';tx(s,'COO PROPOSAL / MANAGED KONG API + AI',60,25,1100,30,16,teal,true);tx(s,title,60,74,1160,105,42,navy,true);tx(s,String(n).padStart(2,'0'),1180,678,40,25,16,muted);return s;}
function table(s,values,x,y,width,height,widths,size=23){const t=s.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width,height,columnWidths:widths,values});for(let r=0;r<values.length;r++){t.rows[r].height=height/values.length;for(let c=0;c<values[0].length;c++){const cell=t.getCell(r,c);cell.fill=r===0?navy:'#FFFFFF';cell.text.style={typeface:font,fontSize:size,color:r===0?'#FFFFFF':navy,bold:r===0};}}t.borders.assign({fill:'#DCE4E2',width:1});return t;}
let s=base('Financial ROI requires benefits beyond cost replacement',1);
table(s,[['Three-year cost baseline','Amount'],['Existing gateway infrastructure + operations','< $300k'],['Existing documentation at $35k per year','$105k'],['Combined current baseline','< $405k'],['Proposed managed Kong TCO','$800k']],60,192,754,290,[574,180],22);
tx(s,'> $395k',875,196,350,77,56,teal,true);tx(s,'Additional benefits for\nthree-year break-even',875,280,335,87,27,navy,true);tx(s,'At least about $132k annually, assuming full retirement of current costs.',875,385,325,100,24,muted);
tx(s,'ROI = (costs avoided + additional validated benefits − $800k) ÷ $800k × 100%',60,507,1155,47,25,navy,true);
tx(s,'Current evidence does not establish positive financial ROI. Qualitative benefits support the decision but do not create a financial return until validated and valued.',60,558,1140,62,23,muted);
tx(s,'Assumptions: flat costs, $35k is annual and separate, full retirement from Year 1, and $800k is complete TCO. Transition overlap or retained costs increase the break-even requirement.',60,642,1100,46,17,muted);
s.speakerNotes.textFrame.setText(`User-provided planning inputs: existing gateway infrastructure and operations cost below $100k annually, documentation cost $35k and proposed managed Kong three-year TCO $800k. Annual and separate treatment of documentation is an assumption carried from the discussion and needs confirmation. Current three-year baseline < $300k + $105k = < $405k. Under full cost displacement, benefits beyond current cost avoidance required for break-even exceed $395k, or $131,666.67 per year. Rounded display > $132k is an approximate planning statement. ROI here uses gross proposal TCO as denominator: (avoidable baseline costs + additional monetized benefits - proposal TCO)/proposal TCO. Use actual avoidable costs, not all baseline costs by default. The $105k is already included in the baseline and cannot be deducted a second time. No positive ROI or payback is asserted. This is undiscounted three-year analysis. Finance can apply its discount rate once timing is established. Validate migration, integration, retained staff, provider consumption, growth, catalogue entitlement and AI entitlement in scope. Keep LLM consumption assumptions consistent across alternatives.`);
s=base('Qualitative value: ownership, delivery and governance',2);
table(s,[['Value to the COO','Expected business outcome','Evidence to track'],['Managed service ownership','Transfer infrastructure operations and patching within agreed scope.','Internal operating hours, patch timeliness and SLA performance'],['Engineering capacity','Reduce custom maintenance around Spring and dependence on key people.','Maintenance backlog, engineering effort and support coverage'],['Delivery readiness','Reuse AI gateway controls and provider integrations for approved use cases.','Onboarding lead time and required use cases supported'],['Governance and resilience','Apply consistent access and usage controls, with clear service accountability.','Policy coverage, usage attribution and incident recovery'],['API discovery and reuse','Replace documentation tooling with a catalogue that exposes APIs and owners.','Tool retirement, catalogue adoption and API ownership coverage']],60,187,1160,402,[265,515,380],22);
tx(s,'These are expected outcomes to validate. Staff time released is capacity unless spend or hiring actually falls. Historical development cost is sunk and does not count as a future saving.',60,620,1135,68,21,muted);
s.speakerNotes.textFrame.setText(`Qualitative benefits reflect the user’s proposed operating model, not measured outcomes. The user states Kong will handle infrastructure, infrastructure operations and patching. Validate precise contracted responsibility boundaries and avoid claiming all application or policy operations disappear. Spring Cloud Gateway is the framework underpinning the current internally developed gateway solution. Do not characterize Spring as incapable of proxying AI traffic. The current implementation requires additional AI management capabilities. Avoided future custom development is a potential benefit only when it is planned and actually displaced. Reduced key-person dependence does not eliminate internal ownership. External capability references from prior research: https://developer.konghq.com/ai-gateway/ and https://docs.spring.io/spring-cloud-gateway/reference/index.html . AI entitlement, catalogue capability and managed support commitments need commercial verification. Reliability improvements are hypotheses, not quantified incident savings. API catalogue replacement must cover current documentation requirements. Historical expenditure is sunk. Do not count maintenance hours already included in the operating baseline twice.`);
s=base('Proposed decision: phased adoption with clear evidence',3);
tx(s,'Business justification',60,203,520,44,30,teal,true);
tx(s,'The premium buys defined operating responsibility and additional API + AI capabilities. A positive financial return remains unproven.',60,263,510,126,28);
tx(s,'Scope and accountability',60,422,520,42,30,teal,true);
tx(s,'Kong: infrastructure operations and patching within the contract.\n\nInternal teams: application integration, policies and vendor oversight.',60,476,520,153,25);
tx(s,'Approval conditions',670,203,545,44,30,teal,true);
const items=[['Commercial scope','Finance and Procurement confirm complete TCO, inclusions and transition costs.'],['Demonstrated outcomes','Platform and AI owners validate required use cases and baseline the measures on slide 2.'],['Cost retirement','Documentation owner confirms replacement coverage and a date to stop the $35k annual cost.'],['Alternative comparison','Compare full Kong adoption with Spring plus AI gateway, including an AI-first rollout.']];
items.forEach((r,i)=>{let y=264+i*90;tx(s,r[0],670,y,540,31,24,teal,true);tx(s,r[1],670,y+32,540,58,22);});
tx(s,'COO approval basis: required capability fit, accountable service delivery and an acceptable premium supported by pilot evidence.',60,653,1100,44,21,navy,true);
s.speakerNotes.textFrame.setText(`Suggested recommendation, not an approved programme: authorize a defined pilot or phased commitment before broad rollout. No pilot budget is supplied, so none is invented. Agree on measurable acceptance thresholds with owners before starting. Compare the complete costs of retaining Spring and adding required AI controls against the complete Kong offering. An AI-first scope may preserve functioning existing gateways and should be priced independently. Include migration effort, parallel running and retained internal responsibilities. The COO can approve a strategic investment without a proven positive financial ROI if mandatory capabilities and the cost premium are explicit. Financial benefits to value when evidence exists: actually retired documentation and gateway costs, planned future engineering or hiring genuinely avoided, measured net AI consumption savings. Keep released capacity and estimated risk reduction separate from cash savings. Do not invent revenue uplift, percentage savings, outage reduction or valuation of risk. Reassess benefits after rollout using agreed owners and review cadence.`);
const candidate=build+'/coo-candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:root+'/output/Kong_COO_Proposal.pptx',pythonExecutable:'/Users/preeti/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit','--require-native-table-slide','1','--require-native-table-slide','2'],explicitTotalSlideCount:3,requiredNativeTableOwnerSlides:[1,2],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/coo-validation-v3.json'});
for(let i=0;i<3;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(build+'/coo-slide-'+(i+1)+'.png',new Uint8Array(await b.arrayBuffer()));}
console.log('Created COO deck');
